<#121> 모델 구조 개선 및 코드 스타일 통일 (2차)
kookmin-sw/capstone-2022-24 pull request #135
Opened 2022-05-01 11:49 UTC by KimKimJungyeon

# 개요
- video 관련 모델 구조 변경된 DB에 맞게 개선, 코드 스타일 통일

# 세부사항
- 기존 model의 arrayfield를 전부 독립시켜 1:다 관계로 변경해 연결
- 주석 설명 수정

# 참고
- MariaDB 연결 문제로 migration 한번 처음부터 다시 했던지라 migration파일이 전부 변경됨.

# PR
- @dadahee 

#Related Issue
- Resolve : #121

2022-05-02 11:12 UTC, dadahee requested changes
정말 고생 많으셨습니다 :)
여태 draft PR로 착각하고 있었네요!

리뷰는 아래 위주입니다!
1. 크롤러 관련 스타일 통일 관련 
2. 모델 필드, 시리얼라이저 관련 사소한 피드백

다만, 최신 ERD가 반영된 건지 다시 확인 부탁드려도 될까요?
링크: [ERD](https://www.erdcloud.com/d/7xG8DNeFaxvMfzXB8)
장르 테이블 등 일부 구조가 코드와 상이한 것 같습니다...!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/README.md
>  # Back-end crawler Data
오아아아아 영문 리드미라니 설레요

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +    result = getMoviebaseCrawler() + getTvbaseCrawler()
`get_base_crawlwer()` 같은 snake_case로 변경해주실 수 있을까요?
pylint, black 스타일에서 어긋날텐데 적용이 안 되었네요! 뭐지

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +    Movie_dict = cs.dictMovieUpdate(Movie_dict)
파이썬에서는 변수명도 마찬가지로 movie_dict 등의 이름으로 통일하는 건 어떨까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +    result = getMoviebaseCrawler() + getTvbaseCrawler()
작성 시 참고하신 구조가 있을까요?
파일 통틀어 작명센스가 전체적으로 깔끔하고 직관적이에요!!! 최고bb

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +    Movie_dict = cs.dictMovieUpdate(Movie_dict)
[TMI] <클린코드> 책에서는 변수명에 자료형을 언급하지 말라는 내용이 있어요.
다만, 파이썬은 오픈 소스에서도 자주 사용되고, 사실 마땅한 이름이 없어서 저도 매번 사용하곤 해요...ㅎㅎ 정연이 의견이 궁금해요. 보통 어떻게 작성하셨고, 여기엔 어떤 이름을 써볼 수 있을까요? 🧐 (수정 요청 아님. 순전히 궁금증!!)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +        url = "https://api.themoviedb.org/3/movie/{0}?api_key={1}&language={2}".format(key, cs.api_key, cs.language)
`f"https://api.themoviedb.org/3/movie/{key}?api_key={cs.api_key}&language={cs.language}"`
이렇게 작성도 가능해요! 저희 컨벤션을 f-string으로 통일했던 것 같은데, 제가 잘못 알고 있는 걸까요? (일단 저는 f"..."로 통일 작성하여 여쭤봅니다...)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +        date_time_obj = datetime.strptime(date_time_str, "%Y-%m-%d").date()
[제안] raw_date_time과 date_time 등의 네이밍은 어떨까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
>      return result
코드 정말 최고예요!!!! 주석도 추가해주셔서 훨씬 이해하기 쉽고요, 짱!!!!!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +    Tv_dict = cs.dictTvUpdate(Tv_dict)
얘네도 소문자로 시작하는 snake_case 변수명은 어떨까 합니다!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +            "posterKey": "https://image.tmdb.org/t/p/original" + json_ob["poster_path"],  # 포스터 크기 고려해야할듯
[참고] 추후 작업이 필요한 부분은 `# TODO` 주석을 달아주시면 IDE에서 편하게 확인할 수 있어요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
> +            "posterKey": "https://image.tmdb.org/t/p/original" + json_ob["poster_path"],  # 포스터 크기 고려해야할듯
포스터 크기는 최대한 큰 크기로 달라고 했는데, 각 크기와 크기별 용량이 어떻게 될까요? 확인 후 전체 언급해주시면 좋을 것 같아요...!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_base.py
>      videoData = getbaseCrawler()
여기도 snake_case로 통일해보는 건 어떨까요?
[제안] 변수명은 좀더 구체적인 데이터 내용으로 선언해보는 건 어떨까요? 더 가독성이 좋아질 것 같아요. DB 스키마랑 유사하니 저라면 모델명을 활용할 것 같네요! (수정 요청 아님, 참고)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +    videoDetailData = []
여기도 스타일 통일이 필요해보입니다! 이후 파일에서는 언급 생략할게요 :)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +    key = videoData["tmdbid"]
변수명을 tmdb_id 그대로 사용하여도 괜찮아 보입니다!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
>      json_ob = json.loads(contents)
ob는 object의 줄임말일까요? (몰라서 질문)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +        "rating": 0,  # 임시 처리
요것도 # TODO로 남겨주세요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +        "runtime": json_ob["runtime"],  # 분 단위로 들어감
추후 문제가 될 가능성이 있으니, BE 논의사항 구글 시트나, 팀원들이 확인할 수 있는 문서에 남겨주시면 좋을 것 같아요!! 일단 내용 확인했습니다 :)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +        "runtime": None,
여기도 나아아아아중에 수정할 수 있죠? 저라면 따로 함수를 뺄 거 같은데... `# TODO` 추가 하는 선에서 마무리해도 좋을 것 같습니다!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +        "gernes": genres_list,
오타 발견입니다!!!!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_details.py
> +}
```python
PROVIDER_NO_TO_LINKS = {
    "8": "https://www.netflix.com/kr/",
    "356": "https://www.wavve.com/",
    "97": "https://watcha.com/",
    "337": "https://www.disneyplus.com/ko-kr",
}
```
이런 건 어떨까요? 파일 최상단에 두면 알아보기 더 좋을 것 같아요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_movie.py
> +def checkSample(id):  # 이미 Movie 데이터가 있는지 check 하는 용도
[참고] `isAlreadyExist` 요런 이름도 있을 것 같네요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +watch_providers = ["8", "337", "356", "97", "119"]  # 순서대로 넷플, 디플, 웨이브, 왓챠, 아마존 프라임 ID
[제안] 저라면 딕셔너리타입이나 개별 상수로 선언할 것 같아요!
구분을 위한 상수이면 `WATCH_PROVIDERS` 요정도로도 충분할 거 같네요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +none_providers_list = ["356"]  # 검색에 문제있는 리스트 (여기서는 웨이브)
마찬가지입니다 :)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +api_key = ""
노출 위험으로 제외해두신 걸까요? 요건 추후에 구두로 import 방법 알려드릴게요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
>  def dictMovieUpdate(Movie_dict):
`update_movie(dict에 있는 값들)` 혹은 `update_movie_dict` 같은 이름은 어떨까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +            if i <= 500:  # page가 분명 1000까지 허용이라는데 왜 500넘으면 오류가 뜨냐고
이것도 투두 남겨주세요 ㅠㅠ

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +            if i <= 500:  # page가 분명 1000까지 허용이라는데 왜 500넘으면 오류가 뜨냐고
지금은 해결 됐을까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +            if i <= 500:  # page가 분명 1000까지 허용이라는데 왜 500넘으면 오류가 뜨냐고
말씀하신 것처럼 이터레이션마다 0.5~3초씩 텀을 두고 1000까지 돌려봐도 괜찮을 것 같아요...

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
> +                page_Num = i - 500
`page_num`은 어떨까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/crawler/crawling_sample.py
>  def dictTvUpdate(Tv_dict):
위에서 언급한대로 update_tv_dict 혹은 update_tv_(변경할데이터상세내용) 등의 이름으로 스타일을 통일해보는 건 어떨까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/config/settings/local.py
> +"""
이건... 뭘까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/config/settings/local.py
> +"""
다른 리뷰들은 참고에 가깝지만 해당 내용은 삭제해주시면 좋을 것 같아요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/video_providers/models.py
>      )
Video와 Provider가 many to many 관계로 연결되며 중간 테이블이 VideoProvider 모델인 걸로 알고 있어요!
그렇다면 provider도 ManyToMany 필드가 아니라 일대다 관계인 ForiegnKey 필드 아닐까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/video_providers/models.py
>          choices=OFFER_CHOICES,
[제안] null=True보다는 "unknown" 등으로 변경하는 건 어떨까요?
알 수 없어서 None인 경우도 있고, 알 수 있지만 입력되지 않아서(insert 시 코드 fault) None인 경우도 있을텐데, 해당 구분이 어렵진 않을까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/video_providers/models.py
> +        return f"{self.video.title}를 제공하는 {self.provider.name}"
외래키로 참조하는 모델의 필드를 참조(이중 참조)하게 될 경우 부하가 증가한다고 해요. 다른 모델과 다르게 Video 관련 부분은 조회/삽입이 묶음 단위로 일어나니 해당 부분은 가급적 조심해야 할 것 같아요! (=> 가급적 다른 모델의 필드를 참조하지 않도록)

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/video_providers/serializer.py
> +class VideoProviderSerializers(serializers.ModelSerializer):
Video와 Provider 모델을 참조하는데 SerializerMethodField가 없어도 될까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/video_total_counts/models.py
>          null=True,
null=True일 필요가 있을까요...? 저는 디버깅이 어려워질 것 같아 보이는데, 허용하신 이유가 궁금해요! (진짜 궁금해서 질문)
그리고 `wishes_count`로의 변경이 필요해보여요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/video_total_counts/models.py
> +        return f"{self.video.title}의 total Counts"
위와 피드백 동일합니다!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/videos/models.py
>      )
[궁금] 외부평점이 숫자 필드가 아닌 이유가 있을까요?

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/videos/models.py
>      )
모델 필드는 기본적으로 null=False, blank=False인 것으로 알고 있어요!
null=False, blank=True 등 다른 경우가 아니라면 굳이 null=False만은 언급하지 않아도 될 것 같습니다!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/videos/models.py
> +        return f"작품 {self.video.title}의 세부정보"
해당 내용도 리뷰 동일해요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/videos/models.py
> +class Gerne(models.Model):
오타가 있네요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/videos/models.py
> +        db_table = "gernes"
마찬가지로 오타가 있어요!

2022-05-02 11:12 UTC, dadahee commented on src/back-end/web/videos/models.py
> +        db_table = "gernes"
erd와 테이블명이 달라보이는데, `video_genres`로 통일하는 건 어떨까요?

2022-05-02 11:27 UTC, KimKimJungyeon commented
통합해서 설명 드리겠습니다. @dadahee 
**1. 크롤러쪽 질문**
crawler 쪽은 수정을 하다가 커밋 올릴때 브런치를 잘못 확인하고 커밋해서ㅠ 바보인듯ㅠ
좀 덜 작업된 파일이 섞였습니다
지금 crawler부분은 따로 작업중인 이슈에서 전면 수정을 하고 있기 때문에 이름이나 통일성 쪽이나 그런건 나중에 그쪽에서 일괄처리해서 올리겠습니다.
**2. video 모델쪽**
- film_rating은 상영등급입니다. 갑자기 적고보니까 이거 아예 빼기로 했었나? 아 긴가민가 하네요.
다시 확인해보고 빼기로 했었으면 아예 ERD랑 코드 둘 다 수정하겠습니다.
- null 부분과 오타는 수정하겠습니다.
**3. 구조 상이 문제**
음 어느부분을 말하시는지 모르겠는데 기존에 details Class 부분의 array field를 SQL 사용때문에 따로 Class화 분리 하고 1:다 관계로 연결한거때문에 그렇게 보이시나요?
제가 시간상 ERD에서는 안고쳐놨었는데 방금 한번 고쳐놨으니 한번 확인해주세요!

2022-05-02 12:30 UTC, dadahee commented
> 통합해서 설명 드리겠습니다. @dadahee **1. 크롤러쪽 질문** crawler 쪽은 수정을 하다가 커밋 올릴때 브런치를 잘못 확인하고 커밋해서ㅠ 바보인듯ㅠ 지금 PR보고 알았는데 아무튼 좀 덜 작업된 파일이 섞였습니다 지금 crawler부분은 따로 작업중인 이슈에서 전면 수정을 하고 있기 때문에 이름이나 통일성 쪽이나 그런건 나중에 그쪽에서 일괄처리해서 올리겠습니다.
> 
> **2. video 모델쪽**
> 
> * film_rating은 상영등급입니다. 갑자기 적고보니까 이거 아예 빼기로 했었나? 아 긴가민가 하네요.
>   다시 확인해보고 빼기로 했었으면 아예 ERD랑 코드 둘 다 수정하겠습니다.
> * null 부분과 오타는 수정하겠습니다.
> 
> **3. 구조 상이 문제** 음 어느부분을 말하시는지 모르겠는데 기존에 details Class 부분의 array field를 SQL 사용때문에 따로 Class화 분리 하고 1:다 관계로 연결한거때문에 그렇게 보이시나요? 제가 시간상 ERD에서는 안고쳐놨었는데 방금 한번 고쳐놨으니 한번 확인해주세요!

1. 애초에 crawler가 지금 PR에서 고려할 내용이 아니라면, 해당 작업 기록을 삭제하는 건 어떨까요?
기존 작업하시던 크롤러 브랜치와 컨플릭트 위험도 있고, 작업 확인도 어렵기 때문입니다.
-> 해당 PR에서 crawler 관련 코드는 일괄 제외해주실 수 있을까요? crawler 작업 기록이 있는 전체 파일을 삭제 후 재커밋 해주시거나 crawlwer 손댄 커밋들 대상으로 revert 하면 될 것 같아요!

2.
- film_rating: 확인했습니다ㅎㅎ 제가 헷갈렸네요.
- `CAPSTONE-24 (면담 피드백 반영)` ERD 수정사항 확인 했습니다...만
- ERD의 정확히 어느 부분들이 왜 바뀌었는지 모르겠습니다... (정말 질문)
  - Q1. non-identifying이 아니라 identifying relationship인 까닭
  - Q2. 장르/제작국가/평점 FK가 video_details에 연결된 까닭
  - Q3. 변경/추가된 테이블이 ratings, prodution_contries, video_details 외에 더 있는지
  - Q4. video_casts의 역할 컬럼 네이밍이 올바른지
- 기존 상세 개선 내용은 컨플루언스 면담 문서를 확인해주세요!
- 제가 말하고자 했던 부분은 작품 상세정보가 아닌 작품 기본 정보와 추가 데이터를 FK로 연결하는 내용이었습니다 :) 면담 피드백 부분과 상이한데 혹시 이유가 있는 걸까요? (정말 질문)
- 그리고 리뷰 커멘트에 대한 커밋은 작업중이신 건지 반영이 끝난 건지도 궁금합니다... (이것도 질문, 리뷰 범위를 모르겠어서요..)

2022-05-02 13:49 UTC, KimKimJungyeon commented
1. 크롤러 삭제로 처리
2. 따로 Q&A를 통해서 ERD 수정, model 구조 변경에 대한 이야기를 마쳤습니다.

리뷰해주신 것들 수정하였으니 확인해주세요! @dadahee

2022-05-03 11:05 UTC, dadahee reviewed
고생 많으셨습니다!!!!!

2022-05-03 11:05 UTC, dadahee commented on src/back-end/web/videos/models.py
> +        Video,
캬학ㅜㅜ 어제 서로 헤맸던 부분 잘 수정해주셨네요!! 감사합니다!!

2022-05-03 11:05 UTC, dadahee commented on src/back-end/web/videos/models.py
> +    """Definition about Rating of Video Information"""
디테일 최고...ㅎㅎ

2022-05-03 11:05 UTC, dadahee commented on src/back-end/web/videos/serializer.py
> +                                                        GenreSerialaizer, ProductionCountrySerialaizer"""
관계가 바뀌니 시리얼라이저까지 수정이 들어가는군요,,,! 많이 번거로우셨을텐데 진짜 고생 많으셨어요 :)

2022-05-03 11:05 UTC, dadahee commented on src/back-end/crawler/README.md
>  # Back-end crawler Data
혹시 이 크롤러 파일들은 다른 브랜치에 옮겨갔을까요? 어떻게 옮기셨을지 궁금하네요. (진짜 궁금해서)

2022-05-03 11:05 UTC, dadahee commented on src/back-end/web/videos/models.py
> +    runtime = models.PositiveIntegerField()
default=0이 있으면 어떨까요?

2022-05-03 11:11 UTC, dadahee requested changes
아주 야아악간 반영이 안 된 부분이 있어 추가 리뷰 드립니다 :)
허허 코드량이 엄청나네요 진짜 고생 많으셨어요!!

2022-05-03 11:11 UTC, dadahee commented on src/back-end/web/config/settings/local.py
> +"""
해당 브랜치 로컬 실행 해보았는데, 반영이 아직 안 된 것 같아요!
여기 다시 확인해줄 수 있을까요? @KimKimJungyeon

2022-05-03 11:11 UTC, dadahee commented on src/back-end/web/videos/migrations/0001_initial.py
> +            ],
VideoDetail은 id 필드가 따로 없이 video_id 필드만으로 구성된 게 맞을까요?
ERD 반영을 위해 확인차 여쭤봅니다!!!!!!!!!!

2022-05-03 11:11 UTC, dadahee commented on src/back-end/web/video_casts/tests.py
> +# Create your tests here.
애네 혹시 pre-commit 안 걸렸었나요????

2022-05-03 11:11 UTC, dadahee commented on src/back-end/web/videos/admin.py
> +from videos.models import Genre, ProductionCountry, Rating, Video, VideoDetail
절대경로 import 너무 좋아요!!!

2022-05-03 12:24 UTC, KimKimJungyeon commented on src/back-end/web/video_casts/tests.py
> +# Create your tests here.
주석 처리 없을땐 pre-commit에서 걸렸는데 전부 주석 처리 했더니 안 잡혔습니다!

2022-05-03 12:26 UTC, KimKimJungyeon commented on src/back-end/web/videos/migrations/0001_initial.py
> +            ],
아 네 맞아요 DB로도 이렇게 보입니다!
![image](https://user-images.githubusercontent.com/39543001/166452394-3947c48a-e194-4d64-8d0a-ec1e8eb02e22.png)

2022-05-03 12:43 UTC, dadahee commented on src/back-end/web/videos/migrations/0001_initial.py
> +            ],
넴!!!!!! ERD 수정했슴니다!!!!1

2022-05-03 15:00 UTC, KimKimJungyeon commented
기존에 지적해주신 거 외에 NULL 처리 관련으로 조금 수정했습니다.
@dadahee

2022-05-03 15:27 UTC, dadahee approved these changes
변경사항 확인했어요! `null=True` 들어가니 훨씬 편할 거 같아요 :)
ERD까지 수정해주셨네요. 정말 수고 많으셨습니다!!!!!!

2022-05-03 15:39 UTC, merged