<#140> 작품 홈화면 리스트 제공 API 구현
kookmin-sw/capstone-2022-24 pull request #157
Opened 2022-05-09 17:27 UTC by KimKimJungyeon

# 개요
- 홈화면에서 작품 리스트를 제공, 검색, 필터링, 정렬이 가능한 API를 구현

# 세부사항
- 1순위에 해당하는 제목으로 검색, provider, category로 필터링, 랜덤 정렬 구현
- video_provider model에서 상위 name 참조하는 부분 삭제
- error 처리를 위한 excetpion 파일 추가

# 참고
- extend_schema 부분은 response작성을 serializer 없이 어떻게 표현해야할 지 잘 모르겠어서.. 일단 재껴놨습니다.
나중에 issue 파든 다른 api 작성할때든 수정을 할게요~

# 관련 이슈
#140 

# PR
- @dadahee

2022-05-09 22:09 UTC, dadahee requested changes
와하하 어렵네요; 진짜 고생 많으셨습니다 😲
dib -> wish 변경 때문에 request change 리뷰로 남깁니다!!!

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +            raise BadFormatException() from e
404 위험은 없을까요?.?

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/video_providers/models.py
> +        return f"{self.video.title}를 제공"
Video 모델에서 f"{self.title}"을 리턴하니 `f"{self.video}를 제공"`으로 작성하여도 괜찮을 것 같아요!
저도 이중 참조 없는 네이밍은 아예 생각이 안나네요 ㅋㅋㅋㅋ

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/urls.py
> +]
헐 아까 네임 없었는데 추가해주셨네요!! 짱짱 좋습니다 bb

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +    responses={200: OpenApiResponse(description="검색 성공", response={"result"})},  # 어떻게 처리해야할지 잘 모르겠어서 임시처리
[지금 수정요청 아님] 두시간 전에 접하셨을텐데 진짜 완벽하게 적어주셨네요!! 깜놀..
시리얼라이저가 없다면, inline_serializer로 선언하거나 example(examples 속성에 OpenApiExample 객체) 등으로 가져가도 괜찮아요! 보통은 스키마가 좋은데, 작품은 예시가 더 직관적일 것 같네요 ?.?

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +            raise BadFormatException() from e
흠 이건 정말 몰라서 여쭤봅니다만,,!
1. 쿼리 파라미터가 손상된 경우(search -> seaach 등)
2. 쿼리 파라미터 값이 너무 많을 경우(필터 0~전체 지원하는지???)
3. 쿼리 파라미터 값이 중복될 경우 (ex. provider=watcha,watcha 등)
에는 어떻게 처리 될까요?

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +        subqueryset = VideoProvider.objects.filter(Q(provider=None))
[정말 몰라서 질문] 서브쿼리셋은 첨봐서 그런디 이 선언부는 empty set이 리턴되는 게 아닌가용,,?

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +        """
주석 완벽 그자체,,, 심봉사도 눈 뜨겠어요

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +            queryset = queryset & query_provider
`else: providers = providers.split()` <- 이걸 저는 단일 항목 선택이라 이해했는데 맞을까요?
`,` 존재 여부와 관계없이 split(",") 쓰면 배열 에러 없이 리턴되는 걸로 알고 있어요!!

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +        "dib": "dibs_count",
앗뜨뜨뜨 `wish`로 들어가야 할 거 같네요!!

2022-05-09 22:09 UTC, dadahee commented on src/back-end/web/videos/views.py
> +            queryset = queryset.order_by(self.sort_dict[sort])
[정말 질문] 정렬 <-> 내림차순이 보통 익숙할 거 같은데 혹시 어떻게 생각하시나요...?
ex) 평점순(=> 평점 높은순), 최신순(=> 날짜가 큰 순) 등등, 가격순일 경우만 보통 오름차순(인데 우리는 없음!)!

2022-05-09 22:13 UTC, dadahee commented
update 브랜치 해놓았어요 🥸
원격 트래킹 브랜치 pull 함만 땡겨주세요!!! (`git pull origin feature/140-be-videoHomeApi`)

2022-05-10 04:08 UTC, KimKimJungyeon commented on src/back-end/web/videos/views.py
> +            raise BadFormatException() from e
1. request.get에서 search키워드로 안 잡혀서 search자체가 안 작동합니다.
2. 현재까지는 문제없게 전체 지원 되었습니다
3. 중복 처리 시엔 결과값 자체는 1개 들어온거랑 똑같이 유지될 거예요(ex. watcha를 2번 필터링-> watcha 1번 필터링한 것과 동일한 값으로 나옴)

2022-05-10 04:10 UTC, KimKimJungyeon commented on src/back-end/web/videos/views.py
> +        subqueryset = VideoProvider.objects.filter(Q(provider=None))
emptyset 맞고 이거 provider은 복수로 들어올 시에 OR연산으로 처리해줘야해서
쌩으로 빈 쿼리셋 만들어줘야 할 필요가 있어서 선언해둔거예요!
그냥 리스트나 사전형태로 선언하면 queryset 구조가 아니라고 빠꾸를 먹여서...

2022-05-10 04:14 UTC, KimKimJungyeon commented on src/back-end/web/videos/views.py
> +            queryset = queryset & query_provider
헐 짱이예요~~

2022-05-10 04:19 UTC, KimKimJungyeon commented on src/back-end/web/videos/views.py
> +            raise BadFormatException() from e
검색결과 Empty값으로 출력될수는 있는데 이때 404 에러 뜨는건 일단 아예 검색,필터링, 정렬 다 끝나고 일괄 처리하는식으로 해놨어요

2022-05-10 04:27 UTC, KimKimJungyeon commented on src/back-end/web/videos/views.py
> +            queryset = queryset.order_by(self.sort_dict[sort])
허 정렬부분은 프론트쪽에서도 생각해봐야할거 같고 정렬이 일단 구현이 순위가 낮아서(랜덤 제외 3,4순위) 찬찬히 담에 다같이 이야기 해도 될거같아요!

2022-05-10 04:28 UTC, KimKimJungyeon commented
@dadahee wishes랑 model 부분만 고쳐서 push 올려놨습니다!

2022-05-10 04:52 UTC, KimKimJungyeon commented
라고 말하기 무섭게 생각나서 permission 부분 추가해놨습니다~~~

2022-05-10 07:06 UTC, dadahee approved these changes
아고 확인이 늦었습니다! 정말 고생 많으셨어요 :)

2022-05-10 07:06 UTC, merged