<#177> 모임 1순위 API - 모임 신청, 취소 구현
kookmin-sw/capstone-2022-24 pull request #202
Opened 2022-05-18 18:17 UTC by KimKimJungyeon

# 개요
- 모임 1순위 API 모임 신청, 취소 구현

# 세부사항
- provider랑 charge 관련 데이터는 다른 이슈에서 처리해서 따로 없음
- API 설계서에 최대한 맞게 구현
- 시리얼라이저로 valid 한번에 확인해서 되도록 일괄 save 되도록 했음.

# 참고
- 모임취소 부분에서 일부 주석 코멘트 남겨놨으니 확인 요망.
- 에러 발생 할 거 같은데에 1차적으로는 try 처리는 했는데 예외는 BadFormatException으로 통일했음. 차후 수정 바람.
_다 해달라고 떠넘기는거 같네요 ㅠㅠ 언제나 감사합니다..._😥

# PR
- @dadahee

2022-05-18 20:33 UTC, dadahee requested changes
정말 고생 많으셨습니다!!
신청 들어올 때마다 매칭 점검하는 로직 추가하고 시리얼라이저, 예외 구체화 하면 될 것 같아요.
모델 관련 내용만 점검 부탁드릴게요 :) !!

2022-05-18 20:33 UTC, dadahee commented on src/back-end/web/applies/models.py
> +    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, null=True)
nullable 필드인 김에, on_delete 옵션도 set null은 어떨까요?

2022-05-18 20:33 UTC, dadahee commented on src/back-end/web/applies/views.py
> +            except LeaderApply.DoesNotExist as e:
LeaderApply.model.DoesNotExist
문법으로 알고 있는데 혹시 해당 코드도 잘 동작 하였을까요 ?.?

2022-05-18 20:33 UTC, dadahee commented on src/back-end/web/groups/views.py
> +            user_serializer.save(total_mileages=(_user.total_mileages - _amount))
시리얼라이저 객체 생성 시 data를 주입해주어서, 파라미터 없어도 잘 동작 할 거예요! :)

2022-05-19 01:45 UTC, KimKimJungyeon commented on src/back-end/web/applies/views.py
> +            except LeaderApply.DoesNotExist as e:
이거 확인해봤는데 문제없이 에러 처리 되었어요~

2022-05-19 01:47 UTC, KimKimJungyeon commented
@dadahee 말해주신거만 후다닥 수정해서 push 올려놨습니다~!

2022-05-19 05:40 UTC, dadahee approved these changes
빠른 수정 감사합니다~~ 로직도 복잡한데 고생 많으셨어요!!!!

2022-05-19 05:40 UTC, merged