<#040> 홈 페이지 렌더링
kookmin-sw/capstone-2022-24 pull request #70
Opened 2022-03-30 10:54 UTC by yesslee

## 개요
홈 페이지 렌더링

## 세부사항
- 검색창 텍스트 초기화 버튼 렌더링
- 필터링 조건 클릭 및 클릭에 따른 값 받아오도록 렌더링
- 필터링 초기화 버튼 렌더링

## 참고
- 필터링 조건 클릭 함수가.. 엄청나게 뚱뚱해졌습니다... 

## PR
- @a-sung

2022-03-30 15:15 UTC, yesslee reviewed
수정한 부분 확인 부탁드릴게요!

2022-03-31 04:15 UTC, a-sung requested changes
클릭 순서가 정확히 기억나지 않는데 랜덤하게 항목을 선택/취소 하다 보면 이렇게 되는거 같아요... 로직을 다시 점검해보는게 좋을 거 같네요ㅠㅠ
![bug](https://user-images.githubusercontent.com/39542903/160975206-7b5e71c7-4aa8-4a2f-87b3-763d3ae0d056.png)

2022-03-31 17:12 UTC, yesslee reviewed
이전 로직에서 크게 바뀐건 없고 '전체' 클릭 이전/이후 값 받아오는 배열 초기화 코드 추가했더니 해결되었어요
초기화 코드 빼먹은 저의 실수였습니다🥲

---

_버그 발견한 케이스도 혹시 몰라 추가해둬요_

개별(true)-전체(true)-개별(false)-전체(false)
-> 개별 선택 해제된 상태인데 배열에 해당 항목 값 남아있음

개별(true)-전체(true)-전체(fasle)-개별(false)
-> 처음 1회는 문제 X, 반복하면 '전체' 라벨이랑 선택했던 항목 값 배열에 남아있음

2022-04-01 01:37 UTC, a-sung approved these changes
동작 잘 하는 거 확인했어요!!! ! ! 넘 수고하셨습니다:D) 화면에 출력 되는 '확인:[]' 부분 지우고 푸시> 머지 부탁드려요S2

2022-04-01 04:34 UTC, merged