<#076> 깃허브 설정 업데이트
kookmin-sw/capstone-2022-24 pull request #77
Opened 2022-04-09 16:39 UTC by dadahee

## 개요
- pre-commit 설정 업데이트
- FE 테스트 활성화

## 세부사항
- pre-commit: detect-aws-credentials 옵션 추가
- FE CI 파일에서 테스트 실행 주석 제거

## 참고
- @KimKimJungyeon 
- 작업 중인 작품 브랜치에서 git pull origin `feature/076-githubSettings` 후 커밋 가능 여부 확인해주세요!
- 체크 후 커멘트 남겨주시면 추가 반영하겠습니다 😀

## PR
- @KimKimJungyeon

2022-04-09 16:44 UTC, dadahee commented
@a-sung, @yesslee 혹시 프론트 테스트(npm test~) 설정이 아직 반영 안 되었던가요? #30 ...???

2022-04-10 05:37 UTC, KimKimJungyeon requested changes
pull하니까 이전에 발생했던 aws관련 에러는 확실히 사라졌는데
![image](https://user-images.githubusercontent.com/39543001/162602524-15544697-abd4-4dd1-bea1-16d1348e8df6.png)

갑자기 djongo import 관련으로 에러가 뜨거든요?
djongo를 가상환경 안이랑 밖 둘다 install 처리 끝낸 상태인데 검색해보니까  이건 또 왜이럴까요 ㅇ>-<
아예 가상환경+ requrements install 하는것도 1번씩 다시 했는데 계속 이러네요

2022-04-10 05:45 UTC, dadahee commented
> pull하니까 이전에 발생했던 aws관련 에러는 확실히 사라졌는데 ![image](https://user-images.githubusercontent.com/39543001/162602524-15544697-abd4-4dd1-bea1-16d1348e8df6.png)
> 
> 갑자기 djongo import 관련으로 에러가 뜨거든요? djongo를 가상환경 안이랑 밖 둘다 install 처리 끝낸 상태인데 검색해보니까 이건 또 왜이럴까요 ㅇ>-< 아예 가상환경+ requrements install 하는것도 1번씩 다시 했는데 계속 이러네요

1. requirements.txt에 `djongo==1.3.6` 확인
2. VSCode pylint 설정: https://dev.to/choijiwoo/vs-code-pylint-unable-to-import-munje-haegyeol-2n96
3. 작품 모델링 브랜치 draft PR 작성
![image](https://user-images.githubusercontent.com/39542793/162603099-4d7a7561-12fa-4c03-87dd-faa7905195a0.png)

1,2번 모두 안 되면 해당 브랜치 PR 올려주실래요? 미완성이어도 괜찮아요!

2022-04-14 05:59 UTC, dadahee commented
> pull하니까 이전에 발생했던 aws관련 에러는 확실히 사라졌는데 ![image](https://user-images.githubusercontent.com/39543001/162602524-15544697-abd4-4dd1-bea1-16d1348e8df6.png)
> 
> 갑자기 djongo import 관련으로 에러가 뜨거든요? djongo를 가상환경 안이랑 밖 둘다 install 처리 끝낸 상태인데 검색해보니까 이건 또 왜이럴까요 ㅇ>-< 아예 가상환경+ requrements install 하는것도 1번씩 다시 했는데 계속 이러네요

hoxy 해결 돼셨을까요 ㅠ0ㅠ

2022-04-14 06:05 UTC, KimKimJungyeon commented
저거 안 그래도 오늘 말해드릴려고 했는데 저게 아무리 해도 해결이 안 되서...
재설치도 해보고 인터프리터도 지정 제대로 해놓고 setting.json 파일도 건들여 봤는데 자꾸 안 되더라구요
일단 import 부분만 오류 뜨면 확인하고 pre-commit 생략해서 commit 올릴까 했어요

2022-04-14 06:10 UTC, dadahee commented
> 저거 안 그래도 오늘 말해드릴려고 했는데 저게 아무리 해도 해결이 안 되서... 재설치도 해보고 인터프리터도 지정 제대로 해놓고 setting.json 파일도 건들여 봤는데 자꾸 안 되더라구요 일단 import 부분만 오류 뜨면 확인하고 pre-commit 생략해서 commit 올릴까 했어요

◠‿◠.... 일단 급한대로 중요한 부분만 파이참에서 작업하고, 나머지는 생략해도 될 거 같아요...
https://velog.io/@hwang-eunji/vscode-python-django-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0
(참고) 이미 닳도록 보셨겠지만 혹시나 해서 가져와봅니다 🥲

2022-04-14 06:15 UTC, dadahee commented
@a-sung @yesslee
프론트 상태 체크 실패 건으로 멘션합니다!
(질문) 테스트 이슈 해결된 걸로 이해했는데, 혹시 아직 유닛/e2e 테스트 막아놔야 할까요?

2022-04-14 07:11 UTC, yesslee approved these changes
제가 알기로는 아마도..? 풀어도 괜찮을 것 같은데 확실한건 아성 의견 들어봐야할 것 같아욥...

2022-04-14 07:47 UTC, a-sung commented
> @a-sung @yesslee 프론트 상태 체크 실패 건으로 멘션합니다! (질문) 테스트 이슈 해결된 걸로 이해했는데, 혹시 아직 유닛/e2e 테스트 막아놔야 할까요?

오잉 죄송합니다 위쪽 알림을 확인못했네요'-` 보니까 vuex가 또 말썽 피우는 거 같은데 test:e2e는 주석 풀어도 괜찮고 test:unit은 조금 더 막아놔주세요ㅠㅠ

2022-04-14 09:39 UTC, dadahee commented
> > @a-sung @yesslee 프론트 상태 체크 실패 건으로 멘션합니다! (질문) 테스트 이슈 해결된 걸로 이해했는데, 혹시 아직 유닛/e2e 테스트 막아놔야 할까요?
> 
> 오잉 죄송합니다 위쪽 알림을 확인못했네요'-` 보니까 vuex가 또 말썽 피우는 거 같은데 test:e2e는 주석 풀어도 괜찮고 test:unit은 조금 더 막아놔주세요ㅠㅠ

<img width="662" alt="image" src="https://user-images.githubusercontent.com/39542793/163358280-e26a0797-6a6f-40dc-b097-994840bad529.png">
(몰라서 질문) e2e 테스트 15분 가량 진행중인데 원래 이정도 걸리나요...?

2022-04-14 11:18 UTC, yesslee commented
> > <img alt="image" width="662" src="https://user-images.githubusercontent.com/39542793/163358280-e26a0797-6a6f-40dc-b097-994840bad529.png">  
> >
> > (몰라서 질문) e2e 테스트 15분 가량 진행중인데 원래 이정도 걸리나요...?  
> 
> 띠용용 그렇게 오래 안걸릴텐데 왜그럴까욥...ㅠ 
> @a-sung e2e 테스트 금방 되는편 아니었나요...?!

2022-04-14 18:10 UTC, dadahee commented
테스트 작성 아직인 것 같아 일단 주석처리 해놨어요. 판도라의 상자는 추후에 다시 열어보는 걸로...

2022-04-14 18:17 UTC, dadahee commented
@KimKimJungyeon pre-commit pylint 에러 해결 하였습니다😂
1. 가상환경(`site-packages`) 인식 안 되는 문제 (<-- 정연이 겪음)
  - 해결법: pylint 레포지토리가 아닌 가상환경 내의 pylint를 pre-commit 훅으로 사용
2. 장고 프로젝트 내 각종 앱/모듈 인식 안 되는 문제 (new! <-- 제가 겪음)
  - 시도: 관련 의존성 모듈 설치 / .pylintrc 파일에 직접 path 설정 / 커스텀 훅 생성 -> 모두 실패 ◠‿◠,,, 울컥
  - 해결법: entry(working directory)를 조작하여 프로젝트 루트 하위 디렉토리를 인식하도록 변경

2022-04-14 20:12 UTC, dadahee commented
@KimKimJungyeon pre-commit pylint 에러 해결 하였습니다😂
- 가상환경(`site-packages`) 인식 안 되는 문제 (<-- 정연이 겪음)
  - 해결법: pylint 레포지토리가 아닌 가상환경 내의 pylint를 pre-commit 훅으로 사용
- 장고 프로젝트 내 각종 앱/모듈 인식 안 되는 문제 (new! <-- 제가 겪음)
  - 시도: 관련 의존성 모듈 설치 / 커스텀 훅 / entry 조작 -> 모두 실패 ◠‿◠,,, (울컥)
  - 해결법: `.pylintrc` 설정파일에 가상환경 모듈(site-packages) + 장고 루트 디렉토리(`/src/back-end/web`) 직접 path 경로 지정

2022-04-15 04:46 UTC, KimKimJungyeon approved these changes
흐악 고생하셨어요 ㅠㅠ

2022-04-15 04:46 UTC, merged